apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-redis
spec:
  replicas: {{ .Values.services.redis.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-redis
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-redis
    spec:
      nodeSelector:
      #        environment: {{ .Release.Name }}
      containers:
        - name: {{ template "fullname" . }}-redis
          image: {{ .Values.services.redis.image }}:{{ .Values.services.redis.tag }}
          resources:
            limits:
              memory: "300Mi"
              cpu: "300m"
            requests:
              memory: "200Mi"
              cpu: "200m"
          ports:
            - containerPort: {{ .Values.services.redis.port }}