apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-zookeeper
spec:
  replicas: {{ .Values.services.zookeeper.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-zookeeper
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-zookeeper
    spec:
      nodeSelector:
      #        environment: {{ .Release.Name }}
      containers:
        - name: {{ template "fullname" . }}-zookeeper
          image: {{ .Values.services.zookeeper.image }}:{{ .Values.services.zookeeper.tag }}
          resources:
            limits:
              memory: "300Mi"
              cpu: "300m"
            requests:
              memory: "200Mi"
              cpu: "200m"
          ports:
            - containerPort: {{ .Values.services.zookeeper.port }}