kind: Service
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-redis
spec:
  type: ClusterIP
  selector:
    app: {{ template "fullname" . }}-redis
  ports:
    - protocol: TCP
      port: {{ .Values.services.redis.port }}
