apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "fullname" . }}-elasticsearch
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/elastic"
